version: 2
submodules:
  include: all
build:
  os: ubuntu-24.04
  tools:
    python: '3.12'
sphinx:
  configuration: docs/conf.py
  fail_on_warning: true
python:
  install:
  - method: pip
    path: .
    extra_requirements:
    - doc
