version: 2
submodules:
  include: all

build:
  os: ubuntu-24.04
  tools:
    python: '3.13'
  jobs:
    post_checkout:
      # unshallow so version can be derived from tag
      - git fetch --unshallow || true
    create_environment:
      - asdf plugin add uv
      - asdf install uv latest
      - asdf global uv latest
    build:
      html:
        - CMAKE_ARGS="-DRSC_BUILD_EXTENSIONS=OFF" uvx hatch run docs:build
        - mv docs/_build $READTHEDOCS_OUTPUT
