version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"
  environment:
    CMAKE_ARGS: "-DRSC_BUILD_EXTENSIONS=OFF"
    # Optionally pin a version if git metadata is missing
    # SETUPTOOLS_SCM_PRETEND_VERSION: "0.0.0"

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - doc

sphinx:
  configuration: docs/conf.py

formats: []
