# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.7.6.dev0+gb0bc71d.d20230804'
__version_tuple__ = version_tuple = (0, 7, 6, 'dev0', 'gb0bc71d.d20230804')
