ARG CUDA_VER=11.8.0
ARG LINUX_VER=ubuntu22.04

FROM nvidia/cuda:${CUDA_VER}-base-${LINUX_VER}

SHELL ["/bin/bash", "-euo", "pipefail", "-c"]

ARG PYTHON_VER=3.11

ENV PATH=/opt/conda/bin:$PATH
ENV PYTHON_VERSION=${PYTHON_VER}

COPY --from=condaforge/miniforge3:24.3.0-0 /opt/conda /opt/conda

COPY rsc_rapids.yml rsc_rapids.yml

ARG GIT_ID=main
ARG DEBIAN_FRONTEND=noninteractive

RUN <<EOF
# install conda environment
set -x
apt-get -qq update
apt-get -q -o=Dpkg::Use-Pty=0 -y dist-upgrade
apt-get -q install -y -o=Dpkg::Use-Pty=0 git
apt-get -q clean -y
mamba env update -n base -f rsc_rapids.yml
mamba install -y -n base pytest -c conda-forge
mamba clean -afy
EOF

RUN <<EOF
# install rapids_singlecell dependencies
set -x
/opt/conda/bin/python -m pip install --no-cache-dir git+https://github.com/scverse/rapids_singlecell.git@${GIT_ID}
/opt/conda/bin/python -m pip uninstall -y --no-cache-dir rapids-singlecell
/opt/conda/bin/python -m pip cache purge
EOF

ENTRYPOINT ["/opt/conda/bin/ipython"]
